baseurl: /link # no custom domain
repository: metreeca/link # local testing (https://help.github.com/articles/repository-metadata-on-github-pages/)
remote_theme: metreeca/docs

exclude: [Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      project: "metreeca-link"
      version: "0.0.0-SNAPSHOT"
      tagline: "Metreeca Linked Data Framework"
      release: "https://github.com/metreeca/link/releases/tag/v0.0.0-SNAPSHOT"
