name: main-mirror

on:

  push:
    tags:
      - '1.1.*'

jobs:

  mirror:

    runs-on: ubuntu-latest

    steps:

      - name: Convert trigger tag name into the corresponding release branch name
        id: source
        run: echo ::set-output
          name=branch::$(echo ${{ github.ref_name }} | sed -r 's:([0-9]+\.[0-9]+).*:release/\1.x:')

      - name: Mirror the release branch to main
        uses: google/mirror-branch-action@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: ${{ steps.source.outputs.branch }}
          dest: 'main'
